var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/discover/route.js")
R.c("server/chunks/ac46c_@vercel_oidc_dist_d85b682c._.js")
R.c("server/chunks/b888e_next_5e3abd8c._.js")
R.c("server/chunks/4b6e4_@opentelemetry_api_build_esm_9cee443b._.js")
R.c("server/chunks/a8d7e_zod_v4_c49d0d28._.js")
R.c("server/chunks/a8d7e_zod_v3_4da438b0._.js")
R.c("server/chunks/c5798_@ai-sdk_google_dist_index_mjs_3b83f4bd._.js")
R.c("server/chunks/fb1ea_ai_dist_index_mjs_fb7d5b0b._.js")
R.c("server/chunks/3e751_@supabase_auth-js_dist_module_8d0de81d._.js")
R.c("server/chunks/node_modules__pnpm_1d32e9dc._.js")
R.c("server/chunks/[root-of-the-server]__fc4047c0._.js")
R.c("server/chunks/_next-internal_server_app_api_discover_route_actions_3eaab5b4.js")
R.m("[project]/node_modules/.pnpm/next@16.0.10_@opentelemetry+api@1.9.0_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/discover/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.0.10_@opentelemetry+api@1.9.0_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/discover/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
