var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1aee1d2b._.js")
R.c("server/chunks/ssr/b888e_next_dist_0b189a09._.js")
R.c("server/chunks/ssr/_ce6ee7d4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9252201._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bbeffcc._.js")
R.c("server/chunks/ssr/node_modules__pnpm_6e39b2be._.js")
R.c("server/chunks/ssr/b888e_next_dist_client_components_builtin_global-error_f1bc17ac.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/b888e_next_dist_client_components_cf7fffc4._.js")
R.c("server/chunks/ssr/b888e_next_dist_client_components_builtin_forbidden_089b9853.js")
R.c("server/chunks/ssr/b888e_next_dist_client_components_builtin_unauthorized_780d42c8.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_39d4fc33.js")
R.m(76900)
module.exports=R.m(76900).exports
